### ISSUE TITLE
Use of `AWS_EXECUTION_ENV` in `logger.rb` and side-effects

### ISSUE THREAD

**Issue by rurounijones** [customink/lamby#186]
Hello there.

I am experimenting with shifting an existing Rails application onto Lambda using the `lamby` gem and so far things are going very well. It works and I am mainly focusing on reducing the cold start time to under 10 seconds in this big app; however I did run into a snag with the logging.

The rails app currently runs on AWS ECS and has an extensively configured structured logging setup. When I added `lamby` I just added it to the default gemset under the impression that it would not do anything unless we actually started the application using Lamby via the `RUN` in the docker file.

However the ECS rails app logs started getting messed up unexpectedly. I believe this is due to the use of `AWS_EXECUTION_ENV` in [logger.rb](https://github.com/rails-lambda/lamby/blob/95d083e1568597f31841ad8920d71a44f2e694e5/lib/lamby/logger.rb#L3). If I am reading the intention correctly then this check is to only prepend the `lamby` logger in an AWS Lambda environment, however AWS ECS _also_ sets this environment variable which triggered Lamby to prepend its logger in the ECS environment.

If I am correct in my reading that we only want to prepend the logger when running on AWS lambda then we can easily change the environment variable from `AWS_EXECUTION_ENV` to `AWS_LAMBDA_FUNCTION_NAME` which, as far as I am aware, _only_ populated by Lambda and Lambda simulators such as SAMLocal and is always present.

If you concur then I am happy to submit a pair of pull requests for `master` and `5-stable`.

**Comment by jeremiahlukus** [comment]
`It works and I am mainly focusing on reducing the cold start time to under 10 seconds in this big app` 

What I am doing it deploying via codebuild using the same arch as the lambda (arm64) then on deploy you bundle install and cache the gems in the docker img. This speeds up the cold start time by several seconds since it does not have fetch the gems.  

Also I have a run warm lambda 

```
  PingHealthCheckLambda:
    Type: AWS::Serverless::Function
    Description: !Sub "Lambda function for health check pings in ${RailsEnv} environment to keep Rails lambda warm"
    Properties:
      FunctionName: !Sub "${RailsEnv}-health" 
      Handler: ping.handler
      Runtime: ruby3.2
      CodeUri: src/
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action: "lambda:InvokeFunction"
            Resource: !GetAtt RailsLambda.Arn
      LoggingConfig:
        LogGroup: !Ref HealthCheckLogGroup


  HealthCheckRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "cron(0/3 * * * ? *)"  # Every 3 minutes
      Targets:
        - Id: "HealthCheckLambdaTarget"
          Arn: !GetAtt PingHealthCheckLambda.Arn
          Input: '{"EVENT_RULE": "HEALTHCHECK"}'
```

Doing this really doesnt cost you anything 

https://lamby.cloud/docs/cold-starts  <- really good info in here as well. I dont think @ metaskills  is fond of the run warm function but I have 4 personal applications and have this in each and im still well within the free tier since costs are pretty minimal to ping a lambda every 3 min really no reason not to do it?
